# Generated by Django 2.2.4 on 2021-04-05 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='模块名称')),
                ('test_owner', models.CharField(max_length=50, verbose_name='测试负责人')),
                ('desc', models.CharField(max_length=100, null=True, verbose_name='简要描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模块信息表',
                'verbose_name_plural': '模块信息表',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interface_name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('request_data', models.CharField(max_length=1024, verbose_name='请求数据')),
                ('assert_key', models.CharField(max_length=1024, verbose_name='编写人员')),
                ('extract_var', models.CharField(max_length=1024, verbose_name='提取变量表达式')),
                ('if_execute', models.CharField(max_length=1024, verbose_name='是否执行')),
                ('status', models.IntegerField(help_text='0：表示有效，1：表示无效，用于软删除', null=True)),
                ('maintainer', models.CharField(max_length=20, verbose_name='维护人员')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('belong_module', smart_selects.db_fields.GroupedForeignKey(group_field='belong_project', on_delete=django.db.models.deletion.CASCADE, to='auto_test.Module', verbose_name='所属模块')),
            ],
            options={
                'verbose_name': '测试用例表',
                'verbose_name_plural': '测试用例表',
            },
        ),
        migrations.CreateModel(
            name='TestSuit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suite_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='测试集合描述')),
                ('if_execute', models.IntegerField(default=0, verbose_name='是否执行')),
                ('test_case_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='测试执行模式')),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试集合',
                'verbose_name_plural': '测试集合',
            },
        ),
        migrations.RenameField(
            model_name='project',
            old_name='poj_owner',
            new_name='proj_owner',
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.CharField(max_length=100, null=True, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='项目更新时间'),
        ),
        migrations.CreateModel(
            name='TestSuitTestCases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=1, verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestCase', verbose_name='测试用例')),
                ('test_suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestSuit', verbose_name='测试集合')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuitExecuteRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run_time_interval', models.IntegerField(default=0, null=True, verbose_name='延迟时间')),
                ('status', models.IntegerField(default=0, null=True, verbose_name='执行状态')),
                ('test_result', models.CharField(blank=True, max_length=50, null=True)),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('execute_start_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行开始时间')),
                ('test_suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestSuit', verbose_name='测试集合')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseExecuteRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('response_data', models.CharField(max_length=1024, verbose_name='执行结果')),
                ('execute_result', models.CharField(max_length=1024, verbose_name='执行结果')),
                ('execute_total_time', models.CharField(max_length=1024, verbose_name='执行耗时')),
                ('execute_start_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行开始时间')),
                ('execute_end_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行结束时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('belong_test_case', smart_selects.db_fields.GroupedForeignKey(group_field='belong_test_case', on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestCase', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': '用例执行结果记录表',
                'verbose_name_plural': '用例执行结果记录表',
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='module',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.Project'),
        ),
    ]
