# Generated by Django 2.2.4 on 2021-04-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0003_auto_20210418_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='assert_key',
            field=models.CharField(max_length=1024, null=True, verbose_name='断言内容'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='extract_var',
            field=models.CharField(max_length=1024, null=True, verbose_name='提取变量表达式'),
        ),
    ]
