# Generated by Django 2.2.4 on 2021-04-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0004_auto_20210418_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='if_execute',
        ),
        migrations.AddField(
            model_name='testcase',
            name='request_method',
            field=models.CharField(max_length=1024, null=True, verbose_name='请求方式'),
        ),
    ]
