# Generated by Django 2.2.4 on 2021-04-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0005_auto_20210419_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='interface_name',
            new_name='case_name',
        ),
        migrations.AddField(
            model_name='testcase',
            name='uri',
            field=models.CharField(default='', max_length=1024, verbose_name='接口地址'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='maintainer',
            field=models.CharField(default='', max_length=1024, verbose_name='编写人员'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='request_data',
            field=models.CharField(default='', max_length=1024, verbose_name='请求数据'),
        ),
        migrations.AlterField(
            model_name='testcaseexecuterecord',
            name='response_data',
            field=models.CharField(max_length=1024, verbose_name='响应字符串'),
        ),
    ]
