# Generated by Django 2.2.4 on 2021-04-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0007_auto_20210421_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': '接口地址配置表', 'verbose_name_plural': '接口地址配置表'},
        ),
        migrations.AddField(
            model_name='testcaseexecuterecord',
            name='exception_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='testcaseexecuterecord',
            name='status',
            field=models.IntegerField(help_text='0：表示未执行，1：表示已执行', null=True),
        ),
    ]
