# Generated by Django 2.2.4 on 2021-05-09 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0008_auto_20210422_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuitTestCaseExecuteRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_result', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(default=0, null=True, verbose_name='执行状态')),
                ('exception_info', models.CharField(blank=True, max_length=500, null=True)),
                ('capture_screen', models.CharField(blank=True, max_length=500, null=True)),
                ('execute_start_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行开始时间')),
                ('execute_end_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行结束时间')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestCase', verbose_name='执行的测试用例')),
                ('test_suit_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestSuitExecuteRecord', verbose_name='执行的测试集合执行记录')),
            ],
        ),
    ]
