# Generated by Django 2.2.4 on 2021-05-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0009_auto_20210509_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuittestcaseexecuterecord',
            name='execute_result',
            field=models.CharField(max_length=1024, null=True, verbose_name='执行结果'),
        ),
        migrations.AddField(
            model_name='testsuittestcaseexecuterecord',
            name='execute_total_time',
            field=models.CharField(max_length=1024, null=True, verbose_name='执行耗时'),
        ),
        migrations.AddField(
            model_name='testsuittestcaseexecuterecord',
            name='request_data',
            field=models.CharField(max_length=1024, null=True, verbose_name='请求体'),
        ),
        migrations.AddField(
            model_name='testsuittestcaseexecuterecord',
            name='response_data',
            field=models.CharField(max_length=1024, null=True, verbose_name='响应字符串'),
        )
    ]
