# Generated by Django 2.2.4 on 2021-05-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0010_auto_20210509_2153'),
    ]

    operations = [
    ]
